version: '3.9'
services:
    mariadb:
      container_name: mariadb
      networks:
        - network            		
      build: 
        context: requirements/mariadb
        dockerfile: Dockerfile
      env_file:
        - .env
      volumes:
        - mariadb_volume:/var/lib/mysql
      restart: unless-stopped
      expose:
        - "3306"
      
    nginx:
      container_name: nginx
      volumes:
        - wordpress_volume:/var/www/html
      networks:
        - network
      depends_on:
        - wordpress
      build: 
        context: requirements/nginx
        dockerfile: Dockerfile
      env_file: .env
      ports:
        - "443:443"
      restart: on-failure

    wordpress:
      container_name: wordpress
      env_file: 
        - .env
      volumes:
        - mariadb_volume:/var/www/html
      networks:
        - network
      build: 
        context: requirements/wordpress
        dockerfile: Dockerfile
      depends_on:
        - mariadb
      restart: on-failure
      expose: 
        - "9000"

volumes:
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/paula/data/wordpress_volume/
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/paula/data/mariadb_volume/

networks:
  network:
    name: inception
    driver: bridge